### ISSUE TITLE
Take over maintenance?

### ISSUE THREAD

**Issue by dustyburwell** [dustyburwell/connect-file-cache#12]
I'm working with @adunkman on maintenance of connect-assets. In the spirit of this comment https://github.com/assaf/zombie/issues/377#issuecomment-17172504 I'm totally willing to take over maintenance of the connect-file-cache module.

**Comment by adunkman** [comment]
Sounds rockin' to me.

**Comment by TrevorBurnham** [comment]
Awesome.

**Comment by dustyburwell** [comment]
Thank you, sir!
