### ISSUE TITLE
Node 0.6.x compatibilty

### ISSUE THREAD

**Issue by toabi** [dustyburwell/connect-file-cache#3]
Since node 0.6.x there's a [zlib binding](http://nodejs.org/docs/v0.6.0/api/zlib.html).

The currently used custom zlib binding doesn't work anymore with 0.6.

**Comment by randypuro** [comment]
FWIW, I sent a github message to the node-zlib-sync library maintainer last week (jasonrm) about the fix (a small tweak to the wscript bulid file); but haven't heard back; therefore, it may make sense to use the builtin binding.

**Comment by TrevorBurnham** [comment]
Thanks guys. I'm working on 0.6.x compatibility for all my libs now. There's also the issue that I'd been using [node-watch-tree](https://github.com/tafa/node-watch-tree) for the test task in the Cakefile, which is broken under 0.6 (I've submitted [a pull request](https://github.com/tafa/node-watch-tree/pull/8) to fix that).

**Comment by dustyburwell** [comment]
Hi, I've recently taken over maintenance for this module. It looks like there was a pull request merged on this and besides that, Node.js is now on 0.10.x. I'm going to assume that this issue can be closed. If it's still a problem, feel free to add another comment and I will re-open it. Cheers.
