### ISSUE TITLE
routePrefix option given to the constructor seems to be ignored

### ISSUE THREAD

**Issue by honzasp** [dustyburwell/connect-file-cache#5]
Hello,

I have `app.js` like this:

``` javascript
express = require("express")
connectCache = require("connect-file-cache")

app = express.createServer()

cache = connectCache({
  src: "javascripts",
  basePath: "/js"
});

app.use(cache.middleware);

app.get("/", function (req, res) {
  res.end("hello\n");
});

app.listen(3000);
```

And the content of `javascripts/script.js` is

``` javascript
alert("Hello world!");
```

I expect the application to send files from "javascripts" directory on requests to "/js/...", meaning `GET /js/script.js` should respond with javascripts/script.js. The documentation of connect-file-cache says that this is possible (`routePrefix: Data will be served from this path (defaults to /)`), but:

```
$ curl localhost:3000/js/script.js
Cannot GET /js/script.js
$ curl localhost:3000/script.js
alert("Hello world!"); # this is javascripts/script.js
$ curl localhost:3000
curl: (52) Empty reply from server
# the app finished with Error: EISDIR, illegal operation on a directory
```

I looked at src/cache.coffee and `@options.routePrefix` is used only in comment and the constructor and seems to be ignored otherwise, causing the above behavior.

Is this a bug or a feature?

Thank you,
Jan Špaček

P.S.: `express` and `connect-file-cache` are installed via npm, node is v0.6.12.

**Comment by dustyburwell** [comment]
Hi, I've recently taken over the maintenance of the module. Since this issue is 10 months old and appears to apply to Node v0.6.x and we're now up to v0.10.x I'm going to go ahead and close it. If this continues to be a problem for you, feel free to re-open the issue and I'll have a look at it. Cheers.
